version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./song/.dev.env
    ports:
      - "8080:8080" # Expose port 8080 on the host machine
      - "2345:2345" # Debug
    volumes:
      - .:/Users/cohenaa/Repos/song-app # Mount the current directory to the container's /app directory
    depends_on:
      - postgres
    working_dir: "/Users/cohenaa/Repos/song-app/song"
   
  postgres:
    image: postgres:latest
    working_dir: "/Users/cohenaa/Repos/song-app/song"
    container_name: postgres-song
    restart: always
    env_file:
      - ./song/.dev.env
    ports:
      - "5432:5432" # Expose port 5432 on the host machine
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d  # Mount the initdb.d directory as a volume
      - postgres_data:/var/lib/postgresql/data # Mount a volume to persist data
      - .:/Users/cohenaa/Repos/song-app

volumes:
  postgres_data: # Volume for PostgreSQL data